# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='distance_allocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='distance_covered',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_allocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_consumption',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_per_km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='overspeed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='top_speed',
            field=models.IntegerField(default=0),
        ),
    ]
