# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0002_auto_20190312_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hash_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'login hash',
                'verbose_name_plural': 'login hashs',
            },
        ),
    ]
