# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0003_login_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_hash',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
