# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0004_login_hash_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_hash',
            new_name='LoginHash',
        ),
    ]
