# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0005_auto_20190313_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereport',
            name='device_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclereport',
            name='login_hash',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclereport',
            name='upto',
            field=models.DateField(null=True),
        ),
    ]
