# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0006_auto_20190313_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='top_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
