# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0007_auto_20190313_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='distance_allocated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_allocated',
            field=models.FloatField(default=0),
        ),
    ]
