# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0008_auto_20190314_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='distance_covered',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_consumption',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='fuel_per_km',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclereport',
            name='overspeed',
            field=models.FloatField(default=0, null=True),
        ),
    ]
