# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0009_auto_20190314_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereport',
            name='target_name',
            field=models.CharField(max_length=100),
        ),
    ]
