# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0010_auto_20190729_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereport',
            name='fuel_economy',
            field=models.FloatField(default=0, null=True),
        ),
    ]
