# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerreport', '0011_vehiclereport_fuel_economy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereport',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclereport',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
